### ISSUE TITLE
关于数字类型的问题

### ISSUE THREAD

**Issue by yancaicai** [zhouyongxiu/PytorchExample#1]
在预测的时候，得到的结果是0，1，2等数字，怎么去对应每个数字是哪一类呢？

**Comment by zhouyongxiu** [comment]
每一类对应的label是在生成训练数据列表的脚本GenList.py的开始几行进行设置：
dict = {'Sedan': 0, 'SUV': 1}

**Comment by yancaicai** [comment]
谢谢！
