### ISSUE TITLE
> 我对自己的数据进行训练，出现了一些错误，不知道是哪里的问题。 RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 layer1~4都正常打印了

### ISSUE THREAD

**Issue by lb1234564** [zhouyongxiu/PytorchExample#3]
> 我对自己的数据进行训练，出现了一些错误，不知道是哪里的问题。 RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 layer1~4都正常打印了

> 我对自己的数据进行训练，出现了一些错误，不知道是哪里的问题。 RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0 layer1~4都正常打印了

有完整的打印信息吗

_Originally posted by @zhouyongxiu in https://github.com/zhouyongxiu/PytorchExample/issues/2#issuecomment-973960330_

**Comment by zhouyongxiu** [comment]
看上去是你的输入图片是4通道的，而dataset的transforms要求输入是3通道的，你尝试一下在dataset里把图片转成3通道图片
